//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace framework.cspnetworks.net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("framework.cspnetworks.net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Has been Added Successfully !.
        /// </summary>
        public static string AddClient_Success {
            get {
                return ResourceManager.GetString("AddClient_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer-Vendor Mapping Has been Added Successfully !.
        /// </summary>
        public static string AddCutomerVendor_Success {
            get {
                return ResourceManager.GetString("AddCutomerVendor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware has been added successfully !.
        /// </summary>
        public static string AddHardware_Success {
            get {
                return ResourceManager.GetString("AddHardware_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software has been added successfully !.
        /// </summary>
        public static string AddSoftware_Success {
            get {
                return ResourceManager.GetString("AddSoftware_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Has been Added Successfully !.
        /// </summary>
        public static string AddUser_Success {
            get {
                return ResourceManager.GetString("AddUser_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Has been Added Successfully !.
        /// </summary>
        public static string AddVendor_Success {
            get {
                return ResourceManager.GetString("AddVendor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Has been Updated Successfully !.
        /// </summary>
        public static string ChangePassword_Success {
            get {
                return ResourceManager.GetString("ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Has been Deleted Successfully !.
        /// </summary>
        public static string DeleteClient_Success {
            get {
                return ResourceManager.GetString("DeleteClient_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer-Vendor Mapping Has been Deleted Successfully !.
        /// </summary>
        public static string DeleteCutomerVendor_Success {
            get {
                return ResourceManager.GetString("DeleteCutomerVendor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Has been Deleted Successfully !.
        /// </summary>
        public static string DeleteHardware_Success {
            get {
                return ResourceManager.GetString("DeleteHardware_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Has been Deleted Successfully !.
        /// </summary>
        public static string DeleteSoftware_Success {
            get {
                return ResourceManager.GetString("DeleteSoftware_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Has been Deleted Successfully !.
        /// </summary>
        public static string DeleteUser_Success {
            get {
                return ResourceManager.GetString("DeleteUser_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Has been Deleted Successfully !.
        /// </summary>
        public static string DeleteVendor_Success {
            get {
                return ResourceManager.GetString("DeleteVendor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Has been Updated Successfully !.
        /// </summary>
        public static string EditClientr_Success {
            get {
                return ResourceManager.GetString("EditClientr_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer-Vendor Mapping Has been Updated Successfully !.
        /// </summary>
        public static string EditCustomerVendor_Success {
            get {
                return ResourceManager.GetString("EditCustomerVendor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Has been Updated Successfully !.
        /// </summary>
        public static string EditHardware_Success {
            get {
                return ResourceManager.GetString("EditHardware_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Has been Updated Successfully !.
        /// </summary>
        public static string EditSoftware_Success {
            get {
                return ResourceManager.GetString("EditSoftware_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Has been Updated Successfully !.
        /// </summary>
        public static string EditUser_Success {
            get {
                return ResourceManager.GetString("EditUser_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Has been Updated Successfully !.
        /// </summary>
        public static string EditVendor_Success {
            get {
                return ResourceManager.GetString("EditVendor_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops !! Something has gone wrong ! Please try again..
        /// </summary>
        public static string Global_Error {
            get {
                return ResourceManager.GetString("Global_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login. Please check your credentials, or contact your administrator..
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
