//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.cspnetworks.net
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSPFRAMEWORKEntities : DbContext
    {
        public CSPFRAMEWORKEntities()
            : base("name=CSPFRAMEWORKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreement> Agreements { get; set; }
        public virtual DbSet<Client_Site> Client_Site { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Customer_Vendors> Customer_Vendors { get; set; }
        public virtual DbSet<Enum_Type_Values> Enum_Type_Values { get; set; }
        public virtual DbSet<Enum_Types> Enum_Types { get; set; }
        public virtual DbSet<Function_Notes> Function_Notes { get; set; }
        public virtual DbSet<Hardware> Hardwares { get; set; }
        public virtual DbSet<Software> Softwares { get; set; }
        public virtual DbSet<User_Groups> User_Groups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
