//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.cspnetworks.net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enum_Type_Values
    {
        public Enum_Type_Values()
        {
            this.Clients = new HashSet<Client>();
            this.Status_Clients = new HashSet<Client>();
            this.Team_Clients = new HashSet<Client>();
            this.Customer_Vendors = new HashSet<Customer_Vendors>();
            this.Customer_Vendors1 = new HashSet<Customer_Vendors>();
            this.Item_Hardwares = new HashSet<Hardware>();
            this.Make_Hardwares = new HashSet<Hardware>();
            this.PurchasedBy_Hardwares = new HashSet<Hardware>();
            this.Status_Hardwares = new HashSet<Hardware>();
            this.Users = new HashSet<User>();
        }
    
        public int enum_type_value_id { get; set; }
        public int enum_type_id { get; set; }
        public string enum_type_value { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Client> Status_Clients { get; set; }
        public virtual ICollection<Client> Team_Clients { get; set; }
        public virtual ICollection<Customer_Vendors> Customer_Vendors { get; set; }
        public virtual ICollection<Customer_Vendors> Customer_Vendors1 { get; set; }
        public virtual ICollection<Hardware> Item_Hardwares { get; set; }
        public virtual ICollection<Hardware> Make_Hardwares { get; set; }
        public virtual ICollection<Hardware> PurchasedBy_Hardwares { get; set; }
        public virtual ICollection<Hardware> Status_Hardwares { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
