//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.cspnetworks.net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function_Notes
    {
        public Function_Notes()
        {
            this.Customer_Vendors = new HashSet<Customer_Vendors>();
        }
    
        public int FunctionNotes_Id { get; set; }
        public string solution { get; set; }
        public string connectivity { get; set; }
        public string ip_address { get; set; }
        public string login_url { get; set; }
        public string management_url { get; set; }
        public string fax_number { get; set; }
        public string phone_number { get; set; }
        public string subnet_mask { get; set; }
        public string DNS1 { get; set; }
        public string DNS2 { get; set; }
        public string WAN_IPs { get; set; }
    
        public virtual ICollection<Customer_Vendors> Customer_Vendors { get; set; }
    }
}
