//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.cspnetworks.net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware
    {
        public int CSPNAssetTag { get; set; }
        public int vendor_id { get; set; }
        public string serial_number { get; set; }
        public Nullable<int> make { get; set; }
        public string model { get; set; }
        public int item { get; set; }
        public Nullable<System.DateTime> warrenty_start_date { get; set; }
        public Nullable<System.DateTime> warrenty_end_date { get; set; }
        public int purchased_by { get; set; }
        public int client_id { get; set; }
        public int location { get; set; }
        public Nullable<int> associated_hardware_id { get; set; }
        public Nullable<int> hardware_status { get; set; }
        public Nullable<int> software_id { get; set; }
    
        public virtual Client_Site Client_Site { get; set; }
        public virtual Client Client { get; set; }
        public virtual Enum_Type_Values Item_Enum_Type_Values { get; set; }
        public virtual Enum_Type_Values Make_Enum_Type_Values { get; set; }
        public virtual Enum_Type_Values Purchased_Enum_Type_Values { get; set; }
        public virtual Enum_Type_Values Status_Enum_Type_Values { get; set; }
        public virtual Hardware AssociatedHardware_Hardware { get; set; }
        public virtual Hardware Hardware2 { get; set; }
        public virtual Software Software { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
