//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.cspnetworks.net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public Software()
        {
            this.Hardwares = new HashSet<Hardware>();
        }
    
        public int CSPNAssetTag { get; set; }
        public int make { get; set; }
        public int model { get; set; }
        public string box_product_key { get; set; }
        public string digital_product_key { get; set; }
        public int license_type { get; set; }
        public int media_type { get; set; }
        public int purchased_by { get; set; }
        public int client_id { get; set; }
        public int location { get; set; }
    
        public virtual Client_Site Client_Site { get; set; }
        public virtual Client Client { get; set; }
        public virtual Enum_Type_Values License_Enum_Type_Values { get; set; }
        public virtual Enum_Type_Values Make_Enum_Type_Values { get; set; }
        public virtual Enum_Type_Values Media_Enum_Type_Values { get; set; }
        public virtual Enum_Type_Values Model_Enum_Type_Values { get; set; }
        public virtual Enum_Type_Values PurchasedBy_Enum_Type_Values { get; set; }
        public virtual ICollection<Hardware> Hardwares { get; set; }
    }
}
