//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.cspportal.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Customer_Vendors = new HashSet<Customer_Vendors>();
            this.Users = new HashSet<User>();
        }
    
        public int client_id { get; set; }
        public string client_code { get; set; }
        public string company_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public string service_type { get; set; }
        public Nullable<int> agreement_id { get; set; }
        public string team { get; set; }
        public string status { get; set; }
        public string sites { get; set; }
    
        public virtual CSP_Services CSP_Services { get; set; }
        public virtual CSP_Teams CSP_Teams { get; set; }
        public virtual ICollection<Customer_Vendors> Customer_Vendors { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
