//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.cspportal.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSP_Teams
    {
        public CSP_Teams()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public string team { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
